services:
  backend:
    build:
      context: ../backend
    container_name: case-intelbras-backend
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    volumes:
      - ../backend:/app:Z

  frontend:
    build:
      context: ../frontend
    container_name: case-intelbras-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_USE_MOCK=false
    volumes:
      - ../frontend:/app:Z
      - /app/node_modules
    depends_on:
      - backend
